import { LandingIcon } from "@/components/landing/landing-icon";

const steps = [
  ["01", "upload" as const, "Bulk Upload", "Import CSV or Excel rosters with validation and duplicate checks.", "Alias-aware schema matching"],
  ["02", "award" as const, "Visual Designer", "Position participant names directly on your certificate artwork.", "Stable normalized coordinates"],
  ["03", "workflow" as const, "Generate Certificates", "Create personalized certificates through durable background jobs.", "Inspectable job states"],
  ["04", "mail" as const, "Automated Delivery", "Send through configured providers without holding an HTTP request open.", "Provider routing and retries"],
  ["05", "people" as const, "Custom Mail", "Keep recipient, subject, and message snapshots with every delivery.", "Safe operational history"],
  ["06", "check" as const, "Actionable Insights", "See queued, sent, retrying, and dead-letter work in one place.", "Operational recovery controls"],
] as const;

export function Workflow() {
  return <section className="reference-section reference-workflow" id="workflow"><span className="workflow-doodle">⌁</span><div className="reference-section-heading"><p>End-to-end pipeline · no more bottlenecks</p><h2>From tabular list to <em>verifiable dispatch.</em></h2><span>A streamlined six-stage pipeline from raw participant data to immutable certificate records.</span></div><div className="reference-step-grid">{steps.map(([number,icon,title,copy,note])=><article key={number}><header><span>{number}</span><i><LandingIcon name={icon} size={15}/></i></header><h3>{title}</h3><p>{copy}</p><small>{note}</small></article>)}</div><div className="reference-architecture" id="operations"><div className="architecture-copy"><p>Pipeline architecture</p><h3>Integrated directly into organizers&apos; flow.</h3><ul><li><LandingIcon name="check" size={12}/><span><b>Bounded participant imports</b><small>Validation happens before persistence.</small></span></li><li><LandingIcon name="check" size={12}/><span><b>Durable generation jobs</b><small>Work remains visible after a crash.</small></span></li><li><LandingIcon name="check" size={12}/><span><b>Deterministic certificate identity</b><small>Retries reuse stable artifact records.</small></span></li><li><LandingIcon name="check" size={12}/><span><b>Explicit delivery recovery</b><small>Retry queues and dead letters stay inspectable.</small></span></li></ul></div><div className="architecture-diagram"><div className="diagram-row"><span>CSV / roster<small>validated input</small></span><i>→</i><span>Event workspace<small>eligible people</small></span><i>→</i><span>Generator<small>durable jobs</small></span><i>→</i><span>Delivery<small>provider route</small></span></div><div className="diagram-ledger"><b>OPERATIONAL RECORD</b><span>JOB STATE · CERTIFICATE ARTIFACT · DELIVERY ATTEMPTS · RECOVERY HISTORY</span></div><footer><span><i/>System ready</span><b>FIG. 2.1 — NAMEFRAME PIPELINE</b></footer></div></div></section>;
}
