export const APP_ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
  AUTHORIZATION_ERROR: "AUTHORIZATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  GENERATION_ERROR: "GENERATION_ERROR",
  STORAGE_ERROR: "STORAGE_ERROR",
  EMAIL_INVALID_RECIPIENT: "EMAIL_INVALID_RECIPIENT",
  EMAIL_PROVIDER_RATE_LIMIT: "EMAIL_PROVIDER_RATE_LIMIT",
  EMAIL_PROVIDER_AUTH_ERROR: "EMAIL_PROVIDER_AUTH_ERROR",
  EMAIL_PROVIDER_UNAVAILABLE: "EMAIL_PROVIDER_UNAVAILABLE",
  EMAIL_PROVIDER_REJECTED: "EMAIL_PROVIDER_REJECTED",
  DATABASE_ERROR: "DATABASE_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  ORGANIZATION_REQUIRED: "ORGANIZATION_REQUIRED",
  ORGANIZATION_ALREADY_EXISTS: "ORGANIZATION_ALREADY_EXISTS",
  EVENT_NOT_FOUND: "EVENT_NOT_FOUND",
  EVENT_NOT_EDITABLE: "EVENT_NOT_EDITABLE",
  EVENT_NOT_DRAFT: "EVENT_NOT_DRAFT",
  EVENT_ALREADY_DELETED: "EVENT_ALREADY_DELETED",
  TEMPLATE_REQUIRED: "TEMPLATE_REQUIRED",
  TEMPLATE_NOT_FOUND: "TEMPLATE_NOT_FOUND",
  TEMPLATE_BACKGROUND_IMMUTABLE: "TEMPLATE_BACKGROUND_IMMUTABLE",
  INVALID_TEMPLATE_COORDINATES: "INVALID_TEMPLATE_COORDINATES",
  INVALID_UPLOAD_TYPE: "INVALID_UPLOAD_TYPE",
  UPLOAD_TOO_LARGE: "UPLOAD_TOO_LARGE",
  UPLOAD_FAILED: "UPLOAD_FAILED",
  PARTICIPANT_NOT_FOUND: "PARTICIPANT_NOT_FOUND",
  PARTICIPANT_NOT_ELIGIBLE: "PARTICIPANT_NOT_ELIGIBLE",
  EVENT_TEMPLATE_MISSING: "EVENT_TEMPLATE_MISSING",
  PARTICIPANT_ALREADY_EXISTS: "PARTICIPANT_ALREADY_EXISTS",
  INVALID_PARTICIPANT_NAME: "INVALID_PARTICIPANT_NAME",
  INVALID_PARTICIPANT_EMAIL: "INVALID_PARTICIPANT_EMAIL",
  IMPORT_INVALID_FILE: "IMPORT_INVALID_FILE",
  IMPORT_UNSUPPORTED_FORMAT: "IMPORT_UNSUPPORTED_FORMAT",
  IMPORT_TOO_LARGE: "IMPORT_TOO_LARGE",
  IMPORT_MISSING_NAME_COLUMN: "IMPORT_MISSING_NAME_COLUMN",
  IMPORT_MISSING_EMAIL_COLUMN: "IMPORT_MISSING_EMAIL_COLUMN",
  IMPORT_AMBIGUOUS_COLUMN_MAPPING: "IMPORT_AMBIGUOUS_COLUMN_MAPPING",
  IMPORT_NO_VALID_ROWS: "IMPORT_NO_VALID_ROWS",
  IMPORT_BATCH_FAILED: "IMPORT_BATCH_FAILED",
  SMTP_CONFIGURATION_INVALID: "SMTP_CONFIGURATION_INVALID",
  SMTP_CONNECTION_FAILED: "SMTP_CONNECTION_FAILED",
  DELIVERY_NOT_FOUND: "DELIVERY_NOT_FOUND",
  DELIVERY_ALREADY_SENT: "DELIVERY_ALREADY_SENT",
  DELIVERY_NOT_RETRYABLE: "DELIVERY_NOT_RETRYABLE",
} as const;

export type AppErrorCode = (typeof APP_ERROR_CODES)[keyof typeof APP_ERROR_CODES];
export type ErrorClassification = "RETRYABLE" | "NON_RETRYABLE";

type AppErrorOptions = {
  status?: number;
  classification?: ErrorClassification;
  cause?: unknown;
};

const DEFAULT_STATUS_BY_CODE: Record<AppErrorCode, number> = {
  VALIDATION_ERROR: 400,
  AUTHENTICATION_ERROR: 401,
  AUTHORIZATION_ERROR: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  RATE_LIMITED: 429,
  GENERATION_ERROR: 500,
  STORAGE_ERROR: 500,
  EMAIL_INVALID_RECIPIENT: 400,
  EMAIL_PROVIDER_RATE_LIMIT: 429,
  EMAIL_PROVIDER_AUTH_ERROR: 500,
  EMAIL_PROVIDER_UNAVAILABLE: 503,
  EMAIL_PROVIDER_REJECTED: 422,
  DATABASE_ERROR: 500,
  INTERNAL_ERROR: 500,
  ORGANIZATION_REQUIRED: 409,
  ORGANIZATION_ALREADY_EXISTS: 409,
  EVENT_NOT_FOUND: 404,
  EVENT_NOT_EDITABLE: 409,
  EVENT_NOT_DRAFT: 409,
  EVENT_ALREADY_DELETED: 409,
  TEMPLATE_REQUIRED: 409,
  TEMPLATE_NOT_FOUND: 404,
  TEMPLATE_BACKGROUND_IMMUTABLE: 409,
  INVALID_TEMPLATE_COORDINATES: 400,
  INVALID_UPLOAD_TYPE: 400,
  UPLOAD_TOO_LARGE: 413,
  UPLOAD_FAILED: 502,
  PARTICIPANT_NOT_FOUND: 404,
  PARTICIPANT_NOT_ELIGIBLE: 409,
  EVENT_TEMPLATE_MISSING: 409,
  PARTICIPANT_ALREADY_EXISTS: 409,
  INVALID_PARTICIPANT_NAME: 400,
  INVALID_PARTICIPANT_EMAIL: 400,
  IMPORT_INVALID_FILE: 400,
  IMPORT_UNSUPPORTED_FORMAT: 400,
  IMPORT_TOO_LARGE: 413,
  IMPORT_MISSING_NAME_COLUMN: 400,
  IMPORT_MISSING_EMAIL_COLUMN: 400,
  IMPORT_AMBIGUOUS_COLUMN_MAPPING: 400,
  IMPORT_NO_VALID_ROWS: 400,
  IMPORT_BATCH_FAILED: 500,
  SMTP_CONFIGURATION_INVALID: 400,
  SMTP_CONNECTION_FAILED: 422,
  DELIVERY_NOT_FOUND: 404,
  DELIVERY_ALREADY_SENT: 409,
  DELIVERY_NOT_RETRYABLE: 409,
};

export class AppError extends Error {
  readonly code: AppErrorCode;
  readonly status: number;
  readonly classification: ErrorClassification;

  constructor(code: AppErrorCode, message: string, options: AppErrorOptions = {}) {
    super(message, { cause: options.cause });
    this.name = "AppError";
    this.code = code;
    this.status = options.status ?? DEFAULT_STATUS_BY_CODE[code];
    this.classification = options.classification ?? "NON_RETRYABLE";
  }
}

export function isAppError(error: unknown): error is AppError {
  return error instanceof AppError;
}
