import Image from "next/image";
import Link from "next/link";

import { LandingIcon } from "@/components/landing/landing-icon";

export function AuthPageShell({ mode, children }: { mode: "sign-in" | "sign-up"; children: React.ReactNode }) {
  const signingIn = mode === "sign-in";
  return <main className="auth-page"><section className="auth-story"><Link className="auth-brand" href="/"><Image src="/nameframelogo.png" width={42} height={42} alt=""/><span>NameFrame</span></Link><div className="auth-story-copy"><p className="landing-kicker">Certificates, without the chaos</p><h1>{signingIn ? "Welcome back to the calm after every event." : "Your next certificate run starts with one clear workspace."}</h1><p>{signingIn ? "Pick up drafts, inspect delivery, and keep your team moving." : "Create the event, import participants, design once, and let the workflow do the repetition."}</p><div className="auth-points"><span><LandingIcon name="check"/>Organization-isolated data</span><span><LandingIcon name="check"/>Durable background generation</span><span><LandingIcon name="check"/>Inspectable email delivery</span></div></div><div className="auth-mini-run"><div><span>Certificate run</span><b>Ready</b></div><i><em/></i><small>Participants · Design · Generate · Deliver</small></div></section><section className="auth-form-side"><div className="auth-mobile-brand"><Image src="/nameframelogo.png" width={34} height={34} alt=""/><span>NameFrame</span></div><div className="auth-form-wrap"><p className="eyebrow">{signingIn ? "Continue your work" : "Create your workspace"}</p><h2>{signingIn ? "Sign in" : "Create an account"}</h2><p>{signingIn ? "Your event operations are waiting." : "Start free and configure your first event."}</p>{children}</div><Link className="auth-back" href="/">← Back to home</Link></section></main>;
}
